import argparse
import json
from pathlib import Path
from urllib.parse import unquote


def _decoded_name(name: str) -> str:
    decoded = unquote(name)
    # Keep decoded names as plain filenames; do not allow path separators.
    decoded = decoded.replace('/', '_').replace('\\', '_')
    return decoded


def _build_unique_path(target: Path) -> Path:
    if not target.exists():
        return target
    stem = target.stem
    suffix = target.suffix
    parent = target.parent
    index = 1
    while True:
        candidate = parent / f"{stem}__dup{index}{suffix}"
        if not candidate.exists():
            return candidate
        index += 1


def _replace_all(text: str, replacements: dict[str, str]) -> str:
    # Replace longer keys first to avoid partial replacement collisions.
    for old_value in sorted(replacements.keys(), key=len, reverse=True):
        text = text.replace(old_value, replacements[old_value])
    return text


def _build_path_variants(old_path: Path, new_path: Path, root_dir: Path) -> dict[str, str]:
    pairs: dict[str, str] = {}

    old_abs = str(old_path)
    new_abs = str(new_path)
    pairs[old_abs] = new_abs
    pairs[old_abs.replace('\\', '/')] = new_abs.replace('\\', '/')

    old_rel = str(old_path.relative_to(root_dir))
    new_rel = str(new_path.relative_to(root_dir))
    pairs[old_rel] = new_rel
    pairs[old_rel.replace('\\', '/')] = new_rel.replace('\\', '/')

    # Common style generated by this project on Windows when outdir is "output".
    pairs[str(Path('output') / old_rel)] = str(Path('output') / new_rel)
    pairs[str(Path('output') / old_rel).replace('\\', '/')] = str(Path('output') / new_rel).replace('\\', '/')

    return pairs


def decode_output_filenames(root_dir: Path) -> tuple[int, int]:
    root_dir = root_dir.resolve()
    if not root_dir.exists() or not root_dir.is_dir():
        raise FileNotFoundError(f'Output directory not found: {root_dir}')

    rename_map: dict[str, str] = {}
    renamed_count = 0

    files = [p for p in root_dir.rglob('*') if p.is_file()]
    for file_path in files:
        new_name = _decoded_name(file_path.name)
        if new_name == file_path.name:
            continue

        target_path = _build_unique_path(file_path.with_name(new_name))
        file_path.rename(target_path)
        renamed_count += 1

        for old_value, new_value in _build_path_variants(file_path, target_path, root_dir).items():
            rename_map[old_value] = new_value

    json_files = [p for p in root_dir.rglob('*.json') if p.is_file()]
    updated_json_count = 0
    for json_path in json_files:
        try:
            original_text = json_path.read_text(encoding='utf-8')
        except UnicodeDecodeError:
            original_text = json_path.read_text(encoding='utf-8-sig')

        updated_text = _replace_all(original_text, rename_map)
        if updated_text == original_text:
            continue

        # Validate JSON after replacement to prevent writing invalid data.
        json.loads(updated_text)
        json_path.write_text(updated_text, encoding='utf-8')
        updated_json_count += 1

    return renamed_count, updated_json_count


def main() -> None:
    parser = argparse.ArgumentParser(
        description='Decode URL-encoded filenames in output directory and update JSON path records.'
    )
    parser.add_argument(
        '-d',
        '--dir',
        default='output',
        help='Target output directory (default: output)',
    )
    args = parser.parse_args()

    renamed_count, updated_json_count = decode_output_filenames(Path(args.dir))
    print(f'Renamed files: {renamed_count}')
    print(f'Updated JSON files: {updated_json_count}')


if __name__ == '__main__':
    main()