import argparse
from pathlib import Path
from src.scraper import analyze_saved_html, save_site_html, scrape_site


def _progress(parsed_count, total_count, current_url):
    print(f'[{parsed_count}/{total_count}] {current_url}')


def _phase(name):
    if name == 'saving_html':
        print('正在保存 HTML')
    elif name == 'analyzing_html':
        print('正在分析已保存 HTML')


def _print_summary(result):
    print('抓取完成')
    print(f'{result["page_count"]}个页面，{result.get("media_count", 0)}个媒体元素')
    print(f'视频数: {result["video_count"]}')
    print(f'失败数: {result.get("failed_count", 0)}')
    if result['pages']:
        print(f'首页HTML: {result["pages"][0]["html_path"]}')
        print(f'首页JSON: {result["pages"][0]["json_path"]}')
    if result.get('failed_reasons'):
        print('失败示例:')
        for u, reason in list(result['failed_reasons'].items())[:3]:
            print(f'- {u} -> {reason}')
    print(f'汇总JSON: {result["summary_path"]}')


def _add_shared_fetch_args(parser):
    parser.add_argument('-o', '--out', default='output', help='Output directory')
    parser.add_argument('-d', '--depth', type=int, default=0, help='Recursive depth for same-domain pages (<0 means unlimited)')
    parser.add_argument('-m', '--max-pages', type=int, default=20, help='Maximum number of pages to crawl (<=0 means unlimited)')
    parser.add_argument('--all', action='store_true', help='Crawl all reachable pages in the same domain')
    parser.add_argument('--renderer', choices=['auto', 'requests', 'playwright'], default='auto', help='Page rendering mode')
    parser.add_argument('--headed', action='store_true', help='Run Playwright with visible browser window')
    parser.add_argument('--wait-seconds', type=float, default=5.0, help='Extra wait time after page load in Playwright mode')
    parser.add_argument('--cdp-url', default='', help='Connect to an existing Chrome via CDP (e.g. http://127.0.0.1:9222)')


def _resolve_depth_and_pages(args):
    max_depth = args.depth
    max_pages = args.max_pages
    if getattr(args, 'all', False):
        max_depth = -1
        max_pages = 0
    return max_depth, max_pages


def main():
    parser = argparse.ArgumentParser(description='Save page HTML and analyze saved HTML to JSON')
    subparsers = parser.add_subparsers(dest='command')

    scrape_parser = subparsers.add_parser('scrape', help='Save HTML and analyze in one command')
    scrape_parser.add_argument('url', help='Target URL to scrape')
    _add_shared_fetch_args(scrape_parser)

    save_parser = subparsers.add_parser('save', help='Only save crawled HTML files')
    save_parser.add_argument('url', help='Target URL to crawl and save as HTML')
    _add_shared_fetch_args(save_parser)

    analyze_parser = subparsers.add_parser('analyze', help='Analyze previously saved HTML files from a manifest')
    analyze_parser.add_argument('manifest', help='Manifest JSON path generated by save')

    parser.set_defaults(command='scrape')
    args = parser.parse_args()

    if args.command == 'analyze':
        result = analyze_saved_html(Path(args.manifest), progress_callback=_progress, phase_callback=_phase)
        _print_summary(result)
        return

    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)
    max_depth, max_pages = _resolve_depth_and_pages(args)

    if args.command == 'save':
        result = save_site_html(
            args.url,
            outdir,
            max_depth=max_depth,
            max_pages=max_pages,
            renderer=args.renderer,
            playwright_headless=not args.headed,
            playwright_wait_seconds=max(args.wait_seconds, 0.0),
            playwright_cdp_url=args.cdp_url.strip(),
            phase_callback=_phase,
        )
        print('保存完成')
        print(f'已保存HTML: {result["saved_count"]}个')
        print(f'失败数: {result.get("failed_count", 0)}')
        print(f'清单JSON: {result["summary_path"]}')
        if result.get('failed_pages_path'):
            print(f'失败页面JSON: {result["failed_pages_path"]}')
        return

    result = scrape_site(
        args.url,
        outdir,
        max_depth=max_depth,
        max_pages=max_pages,
        renderer=args.renderer,
        playwright_headless=not args.headed,
        playwright_wait_seconds=max(args.wait_seconds, 0.0),
        playwright_cdp_url=args.cdp_url.strip(),
        progress_callback=_progress,
        phase_callback=_phase,
    )
    _print_summary(result)


if __name__ == '__main__':
    main()
