from __future__ import annotations

import json
import re
import sqlite3
from datetime import datetime
import hashlib
from collections import deque
from concurrent.futures import ThreadPoolExecutor, wait, FIRST_COMPLETED, as_completed
from pathlib import Path
import time
from urllib.parse import urldefrag, urljoin, urlparse, unquote

import threading

import shutil
import subprocess

import requests
from bs4 import BeautifulSoup, NavigableString, Tag

try:
    from playwright.sync_api import sync_playwright
except Exception:
    sync_playwright = None


# 404/错误页检测关键字
PAGE_404_MARKERS = ('Erreur 404 | Fonds des Nations Unies pour la population', '404 Error Page', 'Error 404 | Panthera')

# 挑战页/封锁页检测关键字
CHALLENGE_MARKERS = (
    'cf-browser-verification',
    'attention required!',
    'checking your browser',
    'enable javascript and cookies',
    'the request could not be satisfied',
    'request blocked',
    'generated by cloudfront',
    '正在进行安全验证',
    '请验证您是真人',
    '安全服务防护恶意自动程序',
    'too many requests',
    '503 service temporarily unavailable',
)

NOISE_PARENT_TAGS = {
    'nav',
    'header',
    'footer',
    'aside',
    'noscript',
}

NOISE_KEYWORDS = ('footer', 'cookie', 'consent', 'breadcrumb', 'share', 'language', 'lang-switcher')
# 精确 class 匹配的噪音容器（不采用子串匹配，避免 sidebar 误匹配 sidebar-wrapper）
NOISE_EXACT_CLASSES = {'inner-container', 'field__item'}

CONTENT_CUTOFF_MARKERS = (
    # 页面中出现该标记后，其后的内容块全部忽略（例如视频版权/署名行等）
)

VIDEO_FILE_RE = re.compile(r'\.(mp4|m3u8|webm|ogg)(\?|$)', re.I)
EMBED_RE = re.compile(r'youtube|youtu\.be|vimeo|player|wistia', re.I)
IMAGE_FILE_RE = re.compile(r'\.(png|jpe?g|webp|gif|bmp|svg)(\?|$)', re.I)
# base64/data URI（如 data:image/png;base64,...）形式的图片无法作为外链媒体提取，忽略
DATA_URI_RE = re.compile(r'^data:', re.I)
HTML_CONTENT_TYPE_RE = re.compile(r'^\s*(?:text/html|application/xhtml\+xml)\s*(?:;|$)', re.I)

DEFAULT_USER_AGENT = (
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
    'AppleWebKit/537.36 (KHTML, like Gecko) '
    'Chrome/138.0.0.0 Safari/537.36'
)


_log_path: Path | None = None

# 每个线程独立的 Playwright + Browser 缓存（Playwright 同步 API 非线程安全）
_thread_local = threading.local()
# 每个线程的页面计数，用于定期重启浏览器释放累积内存
_thread_page_count: dict[int, int] = {}
BROWSER_RESTART_EVERY_N_PAGES = 30


def _get_thread_browser(cdp_url: str = '', headless: bool = True):
    """获取当前线程的 Playwright browser 实例。每个线程独立一个，避免 greenlet 冲突。"""
    if hasattr(_thread_local, 'browser') and _thread_local.browser is not None:
        try:
            _thread_local.browser.contexts  # 探活
            return _thread_local.browser
        except Exception:
            _thread_local.browser = None

    if not hasattr(_thread_local, 'playwright') or _thread_local.playwright is None:
        _thread_local.playwright = sync_playwright().start()

    if cdp_url:
        _log(f'线程内通过CDP连接Chrome: {cdp_url}')
        _thread_local.browser = _thread_local.playwright.chromium.connect_over_cdp(cdp_url)
    else:
        _log('线程内启动本地 Playwright 浏览器')
        _thread_local.browser = _thread_local.playwright.chromium.launch(headless=headless)
    return _thread_local.browser


def _get_thread_context(cdp_url: str = '', headless: bool = True):
    """获取当前线程共享的 browser context。
    CDP 模式复用浏览器已有 context（browser.contexts[0]），这样 page 是现有窗口中的 tab。
    每个线程通过自己独立的 CDP 连接访问，避免 greenlet 冲突。
    """
    if hasattr(_thread_local, 'context') and _thread_local.context is not None:
        try:
            _thread_local.context.pages  # 探活
            return _thread_local.context
        except Exception:
            _thread_local.context = None

    browser = _get_thread_browser(cdp_url, headless)
    if cdp_url and browser.contexts:
        # 复用浏览器已有的默认 context（= 现有 Chrome 窗口），只开 tab 不开新窗口
        _thread_local.context = browser.contexts[0]
    else:
        _thread_local.context = browser.new_context(
            ignore_https_errors=True, user_agent=DEFAULT_USER_AGENT
        )
    return _thread_local.context


def _cleanup_thread_browser():
    """释放当前线程的 Playwright browser 资源，回收内存。"""
    if hasattr(_thread_local, 'browser') and _thread_local.browser is not None:
        try:
            _thread_local.browser.close()
        except Exception:
            pass
        _thread_local.browser = None
    if hasattr(_thread_local, 'context') and _thread_local.context is not None:
        _thread_local.context = None
    if hasattr(_thread_local, 'playwright') and _thread_local.playwright is not None:
        try:
            _thread_local.playwright.stop()
        except Exception:
            pass
        _thread_local.playwright = None


def set_log_file(path: Path):
    """设置日志文件路径。设置后 _log 会同时写入该文件。"""
    global _log_path
    _log_path = Path(path)
    _log_path.parent.mkdir(parents=True, exist_ok=True)


def _log(message: str):
    now = datetime.now().strftime('%H:%M:%S')
    tid = threading.current_thread().native_id
    line = f'[{now}][{tid}] {message}'
    print(line)
    if _log_path is not None:
        try:
            with open(_log_path, 'a', encoding='utf-8') as f:
                f.write(line + '\n')
        except Exception:
            pass

def is_file_url(url):
    """检测 URL 是否指向文件"""
    path = urlparse(url).path
    
    # 1. 检查常见文件扩展名
    file_extensions = (
        '.pdf', '.epub', '.mobi', '.azw', '.azw3',
        '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx',
        '.zip', '.rar', '.7z', '.tar', '.gz',
        '.jpg', '.jpeg', '.png', '.gif', '.bmp', '.svg',
        '.mp3', '.mp4', '.avi', '.mov', '.wmv',
        '.exe', '.msi', '.dmg'
    )
    if path.lower().endswith(file_extensions):
        return True
    
    # 2. 检查常见文件路径模式
    file_patterns = [
        r'/media/\d+/file$',           # UNICEF 风格: /media/7606/file
        r'/assets/.*\.',
        r'/static/.*\.',
    ]
    for pattern in file_patterns:
        if re.search(pattern, path, re.IGNORECASE):
            return True
    
    # 3. 检查后缀中有 '.' 但不是 .html/.htm（你原来的逻辑）
    if '.' in Path(path).suffix:
        suffix = Path(path).suffix.lower()
        if suffix not in ['.html', '.htm']:
            return True
    
    return False

def _safe_name_from_url(url: str, max_len: int = 120) -> str:
    p = urlparse(url)
    host = p.netloc.replace(':', '_')
    path = _sanitize_filename_component(unquote(p.path.strip('/').replace('/', '_')) or '')
    raw_query = unquote(re.sub(r'[^a-zA-Z0-9]+', '_', p.query).strip('_'))
    query = _sanitize_filename_component(raw_query) if raw_query else ''
    if path and query:
        name = f"{host}_{path}_{query}"
    elif path:
        name = f"{host}_{path}"
    elif query:
        name = f"{host}_{query}"
    else:
        name = host
    if len(name) > max_len:
        name = name[:max_len].rstrip('_')
    return name


def _path_name_from_url(url: str, max_len: int = 120) -> str:
    p = urlparse(url)
    path = _sanitize_filename_component(unquote(p.path.strip('/').replace('/', '_')) or '')
    raw_query = unquote(re.sub(r'[^a-zA-Z0-9]+', '_', p.query).strip('_'))
    query = _sanitize_filename_component(raw_query) if raw_query else ''
    if path and query:
        name = f"{path}_{query}"
    elif path:
        name = path
    elif query:
        name = query
    else:
        name = 'index'
    if len(name) > max_len:
        name = name[:max_len].rstrip('_')
    return name


def _sanitize_filename_component(value: str) -> str:
    # Replace characters that are invalid in Windows filenames.
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]', '_', value)
    cleaned = cleaned.strip(' .')
    return cleaned or ''


def _build_output_base_name(url: str, page_index: int, timestamp: str) -> str:
    page_name = _path_name_from_url(url)
    return f"{page_index:04d}_{page_name}_{timestamp}"


def _resolve_url(base: str, link: str) -> str:
    if not link:
        return ''
    return urljoin(base, link)


def _normalize_url(url: str) -> str:
    url, _ = urldefrag(url)
    parsed = urlparse(url)
    if parsed.scheme not in ('http', 'https'):
        return ''
    path = parsed.path or '/'
    return parsed._replace(path=path, query='', fragment='').geturl()


def _is_same_domain(url: str, root_host: str) -> bool:
    host = urlparse(url).netloc.lower()
    root = root_host.lower()
    return host == root or host.endswith(f'.{root}')


def _is_in_noise_area(tag: Tag) -> bool:
    for parent in tag.parents:
        if not isinstance(parent, Tag):
            continue
        if parent.name in NOISE_PARENT_TAGS:
            return True
        if parent.get('aria-hidden') == 'true':
            return True
        classes = ' '.join(parent.get('class', [])).lower()
        pid = (parent.get('id') or '').lower()
        if any(k in classes for k in NOISE_KEYWORDS):
            return True
        if any(k in pid for k in NOISE_KEYWORDS):
            return True
    return False
def _is_visually_hidden(tag: Tag) -> bool:
    """判断元素是否为视觉隐藏元素（如 skip-link、screen-reader-only 内容）。

    这些元素对屏幕阅读器可见但对视觉用户不可见，不应提取为正文内容。
    """
    classes = ' '.join(tag.get('class', [])).lower()
    if 'skip-link' in classes:
        return True
    if 'visually-hidden' in classes:
        return True
    if 'sr-only' in classes:
        return True
    return False


def _is_in_exact_noise_class(tag: Tag) -> bool:
    """检查元素或其祖先是否只有唯一 class 且该 class 精确匹配 NOISE_EXACT_CLASSES。

    仅当 class 数量为 1 且完全匹配时才视为噪音容器，
    避免像 field__item swiper-slide 这种带多个 class 的内容容器被误排除。
    """
    def _exact_single(t: Tag) -> bool:
        classes = t.get('class') or []
        return len(classes) == 1 and classes[0] in NOISE_EXACT_CLASSES

    if _exact_single(tag):
        return True

    for parent in tag.parents:
        if not isinstance(parent, Tag):
            continue
        if _exact_single(parent):
            return True
    return False



def _is_button_like(tag: Tag) -> bool:
    """判断是否为按钮元素（<button>、role="button" 或带按钮样式 class 的 <a> 等）。

    按钮内容（如 "Doná ahora" 捐赠按钮）不应作为正文提取。
    """
    if tag.name == 'button':
        return True
    if tag.get('role') == 'button':
        return True
    for cls in tag.get('class') or []:
        cl = cls.lower()
        # 常见按钮 class：btn / btn-* / button / cta-button / donate*
        if cl == 'btn' or cl.startswith('btn-'):
            return True
        if cl.startswith('button'):
            return True
        if cl == 'cta' or cl.startswith('cta-'):
            return True
    return False


def _clean_text(text: str) -> str:
    return re.sub(r'\s+', ' ', text or '').strip()


def _candidate_text_nodes(container: Tag):
    for node in container.find_all(['h1', 'h2', 'h3', 'h4', 'p', 'li', 'span', 'figcaption']):
        if _is_in_noise_area(node):
            continue
        text = _clean_text(node.get_text(' ', strip=True))
        if len(text) >= 12:
            yield text


def _nearby_description(tag: Tag) -> str:
    figure = tag.find_parent('figure')
    if figure and not _is_in_noise_area(figure):
        caption = figure.find('figcaption')
        if caption:
            text = _clean_text(caption.get_text(' ', strip=True))
            if text:
                return text

    if tag.has_attr('title'):
        text = _clean_text(tag.get('title', ''))
        if text:
            return text
    if tag.has_attr('aria-label'):
        text = _clean_text(tag.get('aria-label', ''))
        if text:
            return text

    # Prefer closest meaningful text in the same content block.
    content_root = tag.find_parent(['article', 'section', 'main', 'div']) or tag.parent
    if isinstance(content_root, Tag):
        for text in _candidate_text_nodes(content_root):
            if text:
                return text[:240]

    prev_text = tag.find_previous(string=True)
    if isinstance(prev_text, NavigableString):
        text = _clean_text(str(prev_text))
        if len(text) >= 12:
            return text[:240]

    return ''


def _is_404_page(soup: BeautifulSoup) -> bool:
    """判断页面是否为 404/错误页。

    遍历所有元素，若任一元素的文本内容（去除首尾空白）与 PAGE_404_MARKERS
    中的某个值完全相等（区分大小写），则判定为 404 页。
    """
    markers = tuple(m.strip() for m in PAGE_404_MARKERS)
    for tag in soup.find_all(text=True):
        text = tag.strip()
        if text in markers:
            _log(f'检测到 404/错误页标记: {text}')
            return True
    return False


def _media_from_tag(tag: Tag, base_url: str):
    src = ''
    media_type = ''

    if tag.name == 'video':
        src = tag.get('src', '')
        if not src:
            source = tag.find('source')
            if source:
                src = source.get('src', '')
        media_type = 'video'
    elif tag.name == 'iframe':
        iframe_src = tag.get('src', '')
        if iframe_src and (EMBED_RE.search(iframe_src) or VIDEO_FILE_RE.search(iframe_src)):
            src = iframe_src
            media_type = 'video'
    elif tag.name == 'a':
        href = tag.get('href', '')
        if href and VIDEO_FILE_RE.search(href):
            src = href
            media_type = 'video'
        elif href and IMAGE_FILE_RE.search(href):
            src = href
            media_type = 'image'
    elif tag.name == 'img':
        src = tag.get('src', '') or tag.get('data-src', '')
        media_type = 'image'

    src = _resolve_url(base_url, src)
    if not src or not media_type:
        return None
    # base64/data URI 图片（如 data:image/png;base64,...）无法作为外链媒体，忽略
    if media_type == 'image' and DATA_URI_RE.match(src):
        return None
    # SVG 图片（矢量图标/图形，通常为装饰性噪声）不作为媒体提取，忽略
    if media_type == 'image' and Path(urlparse(src).path).suffix.lower() == '.svg':
        return None

    note = _nearby_description(tag)
    alt = _clean_text(tag.get('alt', '')) if tag.name == 'img' else ''

    return {
        'id': '',
        'type': media_type,
        'index': 0,
        'tos_url': src,
        'original_url': src,
        'note': note,
        'alt': alt,
    }


def _is_after_in_doc(tag_a: Tag, tag_b: Tag) -> bool:
    """判断 tag_a 是否在文档顺序上位于 tag_b 之后。"""
    a_chain = [tag_a]
    a_chain.extend(tag_a.parents)

    # 找到最低公共祖先（LCA）
    b_ids = {id(p) for p in [tag_b] + list(tag_b.parents)}
    lca = next((p for p in a_chain if id(p) in b_ids), None)
    if lca is None:
        return False

    # LCA 到 tag_a / tag_b 路径上的直接子节点
    child_a = tag_a
    for p in a_chain:
        if p is lca:
            break
        child_a = p

    child_b = tag_b
    for p in [tag_b] + list(tag_b.parents):
        if p is lca:
            break
        child_b = p

    if child_a is child_b:
        return False

    # 在 LCA 的直接子节点中按文档顺序比较
    for child in lca.children:
        if child is child_b:
            return True
        if child is child_a:
            return False
    return False


def _find_content_cutoff_index(candidates, soup, cutoff_markers):
    """返回截断点下标（切片用 candidates[:idx]）；未命中返回 None。

    - 标记元素本身就是候选标签（如正文里的 <h2>Novedades</h2>）：返回该标记的下标，
      使标记本身及其后的内容都被排除。
    - 标记元素不是候选标签（如视频版权署名行 <span>）：返回第一个位于标记之后的
      候选标签下标，标记之前的内容（如视频）保留。
    """
    marker_el = None
    for node in soup.find_all(
        string=lambda s: any(m in s for m in cutoff_markers)
    ):
        # 仅匹配普通文本节点（排除注释/CDATA），取文档顺序最早的一处；
        # 跳过位于导航/页眉/页脚等噪音区域的标记（例如菜单里的 "Novedades"）
        if (type(node) is NavigableString and isinstance(node.parent, Tag)
                and not _is_in_noise_area(node.parent)):
            marker_el = node.parent
            break
    if marker_el is None:
        return None

    for idx, tag in enumerate(candidates):
        if tag is marker_el:
            return idx
        if _is_after_in_doc(tag, marker_el):
            return idx
    return None


def extract_content_blocks(html: str, base_url: str, cutoff_markers=None):
    """从 HTML 中提取文本块、视频和图片。视频和图片各自拥有独立的序号。

    cutoff_markers: 若页面中出现这些标记，则标记之后的所有内容块都会被忽略。
    默认使用 CONTENT_CUTOFF_MARKERS；传入空元组可关闭该行为。
    """
    if cutoff_markers is None:
        cutoff_markers = CONTENT_CUTOFF_MARKERS

    soup = BeautifulSoup(html, 'html.parser')

    # 404/错误页：页面 <link> 元素 href 含 page-404/error-404 时，不提取该页面的
    # 视频、图片等内容（整个页面视为无效）。
    if _is_404_page(soup):
        _log(f'检测到 404/错误页，跳过内容提取, url: {base_url}')
        return []

    root = soup.find('main') or soup.body or soup

    tags = ['h1', 'h2', 'h3', 'h4', 'p', 'li', 'video', 'iframe', 'a', 'img']
    candidates = root.find_all(tags)

    # 内容截断：找到截断点，丢弃标记（及其后的全部内容）。
    # _find_content_cutoff_index() 已返回合适的切片下标：标记本身是候选时返回其下标
    # （连标记一起排除），标记不是候选时返回其后第一个候选下标（如视频版权行场景保留视频）。
    if cutoff_markers and any(m in html for m in cutoff_markers):
        cutoff_index = _find_content_cutoff_index(candidates, soup, cutoff_markers)
        if cutoff_index is not None:
            if cutoff_index > 0:
                cutoff_index -= 1
            candidates = candidates[:cutoff_index]

    blocks = []
    seen_urls = set()
    video_index = 0
    image_index = 0

    for tag in candidates:
        if not isinstance(tag, Tag) or _is_in_noise_area(tag):
            continue

        # 跳过视觉隐藏元素（如 skip-link、screen-reader-only 内容）
        if _is_visually_hidden(tag):
            continue

        media = _media_from_tag(tag, base_url)
        if media:
            key = media['original_url']
            if key in seen_urls:
                continue
            seen_urls.add(key)
            if media['type'] == 'video':
                video_index += 1
                media['index'] = video_index
                media['id'] = hashlib.md5(f"{base_url}|{key}|v{video_index}".encode('utf-8')).hexdigest()
                blocks.append(media)
            elif media['type'] == 'image':
                image_index += 1
                media['index'] = image_index
                media['id'] = hashlib.md5(f"{base_url}|{key}|i{image_index}".encode('utf-8')).hexdigest()
                blocks.append(media)
            continue

        # 跳过 <a> 标签中的文本内容（媒体链接已在上面处理）
        if tag.name == 'a':
            continue

        # 按钮内容不提取（如 "Doná ahora" 捐赠按钮）
        if _is_button_like(tag):
            continue

        # 跳过精确 class 匹配的噪音容器内的元素（如 quicknav-wrapper、sidebar）
        if _is_in_exact_noise_class(tag):
            continue

        # 跳过纯链接导航项：<li> 内只有 <a> 子元素且文本较短（如语言选择器、菜单项）
        if tag.name == 'li' and all(
            child.name == 'a' or (isinstance(child, str) and not child.strip())
            for child in tag.children
        ):
            link_text = _clean_text(tag.get_text(' ', strip=True))
            if len(link_text) < 30:
                continue

        # 跳过内容完全由 <a> 链接构成的标签（如 "Protección | Auditoría | Transparencia"）
        if tag.name in ('p', 'li'):
            a_texts = [a.get_text(' ', strip=True) for a in tag.find_all('a') if a.get_text(' ', strip=True)]
            if a_texts:
                full_text = _clean_text(tag.get_text(' ', strip=True))
                combined_a_text = ' '.join(a_texts)
                # 去除链接组中常见的分隔符（|、•、/ 等）后再比较
                sep_clean = re.sub(r'\s*[|•/]\s*', ' ', full_text)
                sep_clean = _clean_text(sep_clean)
                if _clean_text(combined_a_text) == sep_clean:
                    continue

        text = _clean_text(tag.get_text(' ', strip=True))
        if len(text) < 2:
            continue
        if blocks and isinstance(blocks[-1], str) and blocks[-1] == text:
            continue
        blocks.append(text)

    return blocks


def _extract_links(html: str, base_url: str, root_host: str):
    soup = BeautifulSoup(html, 'html.parser')
    links = []
    for a in soup.find_all('a', href=True):
        href = a.get('href', '').strip()
        if not href or href.startswith('#'):
            continue
        if href.startswith(('mailto:', 'tel:', 'javascript:')):
            continue
        #有扩展名，扩展名不是.html或.htm的链接
        if not re.search(r'\.html?$', urlparse(href).path, re.IGNORECASE) and '.' in Path(urlparse(href).path).suffix:
            continue
        resolved = _normalize_url(_resolve_url(base_url, href))
        if not resolved:
            continue
        if not _is_same_domain(resolved, root_host):
            continue
        links.append(resolved)
    return links


def _is_html_document(html: str) -> bool:
    sample = (html or '')[:4000].lower()
    return ('<html' in sample) or ('<!doctype html' in sample)


def _is_challenge_or_block_page(html: str) -> bool:
    sample = (html or '').lower()
    # Do not treat generic "cloudflare" mentions as challenge pages;
    # many normal sites include Cloudflare assets and would be false positives.
    return any(m in sample for m in CHALLENGE_MARKERS)


def _try_click_challenge_checkbox(page) -> bool:
    selectors = [
        "input[type='checkbox']",
        "[role='checkbox']",
        "label:has-text('请验证您是真人')",
        "label:has-text('Verify you are human')",
        "text=请验证您是真人",
        "text=Verify you are human",
    ]

    # Try direct click on main document.
    for selector in selectors:
        try:
            locator = page.locator(selector).first
            if locator.count() > 0:
                locator.click(timeout=250, force=True)
                return True
        except Exception:
            continue

    # Try click inside embedded challenge frames.
    for frame in page.frames:
        if frame == page.main_frame:
            continue
        for selector in selectors:
            try:
                locator = frame.locator(selector).first
                if locator.count() > 0:
                    locator.click(timeout=250, force=True)
                    return True
            except Exception:
                continue

    # Cloudflare challenge is often rendered in an iframe; try clicking iframe itself.
    frame_selectors = [
        "iframe[title*='security challenge']",
        "iframe[title*='Cloudflare']",
        "iframe[src*='challenges.cloudflare.com']",
    ]
    for selector in frame_selectors:
        try:
            locator = page.locator(selector).first
            if locator.count() > 0:
                locator.click(timeout=250, force=True)
                return True
        except Exception:
            continue

    return False


def fetch_html_with_playwright(
    url: str,
    wait_seconds: float = 5.0,
    headless: bool = True,
    cdp_url: str = '',
) -> dict:
    """返回 {'html': str, 'content_type': str}"""
    if sync_playwright is None:
        raise RuntimeError('Playwright is not installed. Run: pip install playwright and playwright install chromium')

    body_deadline = time.time() + max(float(wait_seconds), 10.0)

    def _navigate_and_capture(page, url, body_deadline, wait_seconds):
        """在已打开的 page 上导航并捕获 HTML。返回 (html, content_type)。"""
        _log(f'开始打开页面: {url}')
        page.route("**/google-analytics.com/**", lambda route: route.abort())
        try:
            response = page.goto(url, wait_until='domcontentloaded', timeout=max(10.0, body_deadline - time.time()) * 1000)
            ctype = response.headers.get('content-type', '') if response is not None else ''
        except Exception as goto_err:
            err_msg = str(goto_err)
            if 'net::ERR_HTTP_RESPONSE_CODE_FAILURE' in err_msg:
                _log(f'HTTP 响应错误，使用 page.request.get 重新获取: {url}, 错误: {goto_err}')
                api_resp = page.request.get(url)
                body_bytes = api_resp.body()
                html_text = body_bytes.decode('utf-8', errors='replace')
                ctype = api_resp.headers.get('content-type', '')
                return html_text, ctype
            raise

        try:
            #_log(f'等待 DOM 加载完成: {url} 超时时间: {max(10.0, body_deadline - time.time()):.1f}秒')
            page.wait_for_load_state('domcontentloaded', timeout=max(10.0, body_deadline - time.time()) * 1000)
        except TimeoutError:
            _log(f'等待 DOM 加载超时: {url}')
            return '', ctype

        if HTML_CONTENT_TYPE_RE.search(ctype) and _is_challenge_or_block_page(page.content()):
            challenge_wait_seconds = max(10.0, wait_seconds)
            challenge_deadline = time.time() + challenge_wait_seconds
            _log(f'检测到挑战页，额外最多等待{challenge_wait_seconds:.1f}秒: {url}')
            while time.time() < challenge_deadline:
                if _try_click_challenge_checkbox(page):
                    _log(f'已尝试自动勾选安全验证: {url}')
                page.wait_for_timeout(1000)
                if not _is_challenge_or_block_page(page.content()):
                    break
        else:
            page.wait_for_timeout(1000)

        return page.content(), ctype

    use_cdp = bool(cdp_url)

    # 非 CDP 模式下，定期重启浏览器以释放累积的内存（缓存、JS 堆等）
    if not use_cdp:
        tid = threading.current_thread().native_id
        count = _thread_page_count.get(tid, 0) + 1
        _thread_page_count[tid] = count
        if count % BROWSER_RESTART_EVERY_N_PAGES == 0:
            _log(f'线程累计抓取 {count} 页，重启浏览器释放内存')
            _cleanup_thread_browser()

    # CDP：复用 thread-local browser + context，只开/关 tab
    browser = _get_thread_browser(cdp_url, headless)
    context = _get_thread_context(cdp_url, headless)
    page = context.new_page()
    html = ''
    content_type = ''
    try:
        html, content_type = _navigate_and_capture(page, url, body_deadline, wait_seconds)
        _log(f'HTML已抓取，准备关闭page: {url}, 字节数: {len(html)}')
    except Exception as e:
        _log(f'抓取页面异常: {url}, 错误: {e}')
        raise
    finally:
        page.close()
        #_log(f'CDP tab已关闭: {url}')
        if not use_cdp:
            context.close()
            #_log(f'浏览器已关闭: {url}')

    return {'html': html, 'content_type': content_type}


def fetch_html(
    url: str,
    renderer: str = 'auto',
    playwright_headless: bool = True,
    playwright_wait_seconds: float = 5.0,
    playwright_cdp_url: str = '',
) -> dict:
    """返回 {'html': str, 'content_type': str}"""
    headers = {
        'User-Agent': DEFAULT_USER_AGENT
    }
    if renderer == 'playwright':
        result = fetch_html_with_playwright(
            url,
            wait_seconds=max(playwright_wait_seconds, 10.0),
            headless=playwright_headless,
            cdp_url=playwright_cdp_url,
        )
        return result

    try:
        r = requests.get(url, headers=headers, timeout=playwright_wait_seconds)
        r.raise_for_status()
        ctype = r.headers.get('content-type', '')
        # Many sites return missing/incorrect charset headers. Prefer apparent encoding
        # so Unicode punctuation like em dash is preserved in saved JSON.
        if not r.encoding or r.encoding.lower() in ('iso-8859-1', 'latin1'):
            r.encoding = r.apparent_encoding or 'utf-8'
        html = r.text
    except requests.RequestException:
        if renderer == 'auto':
            result = fetch_html_with_playwright(
                url,
                wait_seconds=max(playwright_wait_seconds, 10.0),
                headless=playwright_headless,
                cdp_url=playwright_cdp_url,
            )
            return result
        raise

    if renderer == 'auto' and _is_challenge_or_block_page(html):
        result = fetch_html_with_playwright(
            url,
            wait_seconds=max(playwright_wait_seconds, 10.0),
            headless=playwright_headless,
            cdp_url=playwright_cdp_url,
        )
        return result

    return {'html': html, 'content_type': ctype}


def _save_html_snapshot(url: str, html: str, outdir: Path, page_index: int, timestamp: str) -> str:
    base_name = _build_output_base_name(url, page_index, timestamp)
    filename = f"{base_name}.html"
    html_path = outdir / filename

    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html)

    return filename


def _save_analyze_output(url: str, src_path: Path, outdir: Path, page_index: int, timestamp: str, content_blocks):
    """将原始 HTML 文件复制到分析目录，并生成 JSON 分析结果。"""
    base_name = _build_output_base_name(url, page_index, timestamp)
    dst_html = outdir / f"{base_name}.html"
    json_path = outdir / f"{base_name}.json"

    # 从原始路径读取 HTML 写入目标
    dst_html.write_text(src_path.read_text(encoding='utf-8'), encoding='utf-8')

    payload = {
        'original_link': url,
        'content_blocks': content_blocks,
        'extra': {},
    }
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    return str(dst_html), str(json_path)


def _failed_dir(outdir: Path) -> Path:
    return outdir / 'failed'


def _scrape_db_path(start_url: str, outdir: Path) -> Path:
    """合并后的 SQLite 数据库路径（含 pages 和 failed_pages 两张表）。"""
    return outdir / f"{_safe_name_from_url(start_url)}_scrape.db"


def _init_db(db_path: Path) -> sqlite3.Connection:
    """打开（或创建）scrape 数据库，创建 pages 和 failed_pages 两张表，返回连接对象。"""
    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute(
        "CREATE TABLE IF NOT EXISTS pages ("
        "  url TEXT PRIMARY KEY,"
        "  html_path TEXT DEFAULT NULL,"
        "  content_type TEXT NOT NULL DEFAULT '',"
        "  links TEXT DEFAULT NULL,"
        "  video_count INTEGER NOT NULL DEFAULT -1,"
        "  image_count INTEGER NOT NULL DEFAULT -1,"
        "  created_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))"
        ")"
    )
    conn.execute(
        "CREATE TABLE IF NOT EXISTS failed_pages ("
        "  url TEXT PRIMARY KEY,"
        "  reason TEXT NOT NULL,"
        "  html_path TEXT DEFAULT NULL,"
        "  created_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))"
        ")"
    )
    # 为 video_count 添加索引，加速 analyze 阶段查询未分析页面
    try:
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_pages_video_count ON pages(video_count)"
        )
    except Exception:
        pass

    # 为已有 pages 表补充新增字段
    for col in ('video_count', 'image_count', 'links'):
        try:
            if col == 'links':
                conn.execute(f"ALTER TABLE pages ADD COLUMN {col} TEXT DEFAULT NULL")
            else:
                conn.execute(f"ALTER TABLE pages ADD COLUMN {col} INTEGER NOT NULL DEFAULT -1")
        except Exception:
            pass
    conn.commit()
    return conn


def _load_html_cache_from_db(start_url: str, outdir: Path) -> list:
    """从 SQLite 加载全部页面缓存到内存 list。"""
    db_path = _scrape_db_path(start_url, outdir)
    if not db_path.exists():
        return []
    try:
        conn = sqlite3.connect(str(db_path))
        conn.execute("PRAGMA journal_mode=WAL")
        cursor = conn.execute("SELECT url, html_path, content_type, video_count FROM pages")
        cache = []
        for url, html_path, content_type, video_count in cursor:
            if html_path:
                p = Path(html_path)
                if not p.is_absolute():
                    p = outdir / p
                html_path = str(p)
            cache.append({'url': url, 'html_path': html_path, 'content_type': content_type, 'video_count': video_count})
        conn.close()
        return cache
    except Exception:
        return []


def _flush_html_batch(conn: sqlite3.Connection, entries: list):
    """批量写（INSERT OR REPLACE）脏页面记录到 SQLite。写入时重置 video_count/image_count 为 -1。"""
    if not entries:
        return
    try:
        rows = [(e['url'], e['html_path'], e.get('content_type', '')) for e in entries]
        conn.executemany(
            "INSERT OR REPLACE INTO pages (url, html_path, content_type, video_count, image_count)"
            " VALUES (?, ?, ?, -1, -1)", rows
        )
        conn.commit()
    except Exception:
        pass


def _load_links_cache_from_db(start_url: str, outdir: Path) -> dict:
    """从 SQLite pages 表加载全部链接缓存到内存 dict。"""
    db_path = _scrape_db_path(start_url, outdir)
    if not db_path.exists():
        return {}
    try:
        conn = sqlite3.connect(str(db_path))
        conn.execute("PRAGMA journal_mode=WAL")
        cursor = conn.execute("SELECT url, links FROM pages where links IS NOT NULL")
        result = {}
        for url, links_json in cursor:
            try:
                result[url] = json.loads(links_json)
            except Exception:
                result[url] = []
        conn.close()
        return result
    except Exception:
        return {}


def _flush_links_batch(conn: sqlite3.Connection, entries: dict):
    """批量更新 pages 表中的链接列表。"""
    if not entries:
        return
    try:
        rows = [(json.dumps(links, ensure_ascii=False), url) for url, links in entries.items()]
        conn.executemany("UPDATE pages SET links = ? WHERE url = ?", rows)
        conn.commit()
    except Exception:
        pass


def _flush_failed_pages_batch(conn: sqlite3.Connection, entries: list):
    """批量追加写入失败页面记录到 SQLite（INSERT OR REPLACE，使用已有连接）。"""
    if not entries:
        return
    try:
        rows = [
            (p['url'], p['reason'], p.get('html_path', None))
            for p in entries
        ]
        conn.executemany(
            "INSERT OR REPLACE INTO failed_pages (url, reason, html_path) VALUES (?, ?, ?)",
            rows,
        )
        conn.commit()
    except Exception:
        pass


def _load_failed_pages_from_db(start_url: str, outdir: Path) -> list:
    """从 SQLite 加载历史失败页面列表。"""
    db_path = _scrape_db_path(start_url, outdir)
    if not db_path.exists():
        return []
    try:
        conn = sqlite3.connect(str(db_path))
        cursor = conn.execute(
            "SELECT url, reason, html_path FROM failed_pages ORDER BY rowid"
        )
        result = []
        for url, reason, html_path in cursor:
            if html_path:
                p = Path(html_path)
                if not p.is_absolute():
                    p = outdir / p
                html_path = str(p)
            result.append({'url': url, 'reason': reason, 'html_path': html_path})
        conn.close()
        return result
    except Exception:
        return []


def save_site_html(
    url: str,
    outdir: Path,
    max_depth: int = 0,
    max_pages: int = 20,
    max_concurrency: int = 1,
    renderer: str = 'auto',
    playwright_headless: bool = True,
    playwright_wait_seconds: float = 5.0,
    playwright_cdp_url: str = '',
    phase_callback=None,
):
    start_url = _normalize_url(url)
    if not start_url:
        raise ValueError('Only http/https URLs are supported.')

    outdir.mkdir(parents=True, exist_ok=True)
    _failed_dir(outdir).mkdir(parents=True, exist_ok=True)
    set_log_file(outdir / 'scrape.log')
    root_host = urlparse(start_url).netloc
    visited = set()
    queued = set()
    queue = deque()
    failed_pages: list = _load_failed_pages_from_db(start_url, outdir)
    failed_urls: set = {p['url'] for p in failed_pages}
    _log(f'Loaded {len(failed_urls)} failed pages from SQLite.')
    html_cache = _load_html_cache_from_db(start_url, outdir)
    _log(f'Loaded {len(html_cache)} cached pages from SQLite.')
    links_cache = _load_links_cache_from_db(start_url, outdir)
    _log(f'Loaded {len(links_cache)} cached links from SQLite.')
    conn = _init_db(_scrape_db_path(start_url, outdir))  # 单个持久连接，含 pages + failed_pages 两张表
    _log(f'Initialized SQLite database at {_scrape_db_path(start_url, outdir)}.')
    dirty_html: list = []  # 自上次 flush 后新增的页面记录
    dirty_links: dict = {}  # 记录自上次 flush 后变更的 url -> links
    dirty_failed: list = []  # 自上次 flush 后新增的失败页面记录
    timestamp = datetime.now().strftime('%Y%m%d%H%M%S')

    # 从本地缓存恢复：优先使用 links_cache 避免重新解析 HTML
    for cached in html_cache:
        cached_url = cached['url']
        # 只读取 content_type 为 html 的文件来提取链接
        ctype = cached.get('content_type', '')
        if not HTML_CONTENT_TYPE_RE.search(ctype):
            visited.add(cached_url)
            _log(f'跳过非 HTML 缓存 URL: {cached_url} (content_type={ctype})')
            continue
        # 已分析为无视频的页面（video_count=0）：本地 HTML 可能已被删除，无需再下载
        if cached.get('video_count', -1) == 0:
            visited.add(cached_url)
            _log(f'跳过已分析且无视频的缓存 URL: {cached_url}')
            continue
        if cached['html_path'] is None:
            #_log(f'缓存记录 html_path 为空: {cached_url}')
            continue
        cached_html_path = Path(cached['html_path'])
        if cached_html_path.exists():
            visited.add(cached_url)
        else:
            #_log(f'缓存 HTML 文件不存在: {cached_html_path} (URL: {cached_url})')
            continue
        # 优先从 links_cache 读取，否则回退到解析 HTML
        links = links_cache.get(cached_url, None)
        if links is None:
            try:
                _log(f'Processing cached URL: {cached_url}')
                cached_html = cached_html_path.read_text(encoding='utf-8')
                # 遇到links!=[]的并且是block/challenge页面的情况，并不会执行到这里，需要单独写个程序洗出 block/challenge页面的缓存
                if _is_challenge_or_block_page(cached_html):
                    _log(f'Cached HTML is a challenge/block page: {cached_url}')
                    cached_html_path.unlink(missing_ok=True)
                    visited.remove(cached_url)
                    continue
                links = _extract_links(cached_html, cached_url, root_host)
                dirty_links[cached_url] = links
            except Exception:
                links = []
                visited.remove(cached_url)

        for link in links:
            if link not in visited and link not in failed_urls and link not in queued:
                # 从 URL 路径解析深度（path 分段数)
                cached_path = urlparse(link).path.strip('/')
                cached_depth = len(cached_path.split('/')) if cached_path else 0
                if is_file_url(link):
                    _log(f"跳过文件链接: {link}")
                    continue
                queue.append((link, cached_depth))
                queued.add(link)

    # 如果 start_url 不在缓存中，加入队列
    if start_url not in visited and start_url not in failed_urls and start_url not in queued:
        queue.appendleft((start_url, 0))
        queued.add(start_url)
    unlimited_depth = max_depth < 0
    unlimited_pages = max_pages <= 0
    max_concurrency = max(1, int(max_concurrency))

    def _append_failed(page_url: str, reason: str, html: str = ''):
        failed_html_path = ''
        if html:
            try:
                failed_html_path = _save_html_snapshot(
                    page_url,
                    html,
                    _failed_dir(outdir),
                    page_index=len(failed_urls) + 1,
                    timestamp=timestamp,
                )
            except Exception:
                failed_html_path = ''
        entry = {
            'url': page_url,
            'reason': reason,
            'html_path': failed_html_path,
        }
        dirty_failed.append(entry)
        failed_urls.add(page_url)

    def _fetch_one(item):
        page_url, _depth = item
        try:
            fetch_result = fetch_html(
                page_url,
                renderer=renderer,
                playwright_headless=playwright_headless,
                playwright_wait_seconds=playwright_wait_seconds,
                playwright_cdp_url=playwright_cdp_url,
            )
            html_text = fetch_result['html']
            content_type = fetch_result.get('content_type', '')
            # 在线程内提取链接，避免主线程串行解析
            links = None
            if HTML_CONTENT_TYPE_RE.search(content_type):
                try:
                    links = _extract_links(html_text, page_url, root_host)
                except Exception:
                    links = None
            return {
                'url': page_url,
                'html': html_text,
                'html_path': None,
                'error': '',
                'content_type': content_type,
                'links': links,
            }
        except Exception as exc:
            return {
                'url': page_url,
                'html': '',
                'html_path': None,
                'error': str(exc),
                'content_type': '',
                'links': None,
            }

    if callable(phase_callback):
        phase_callback('saving_html')

    pending = {}  # {Future: (url, depth)}

    def _try_submit():
        """从队列取一个 URL 提交到线程池，返回是否成功提交。"""
        while queue:
            if not unlimited_pages and len(html_cache) >= max_pages:
                return False
            current_url, depth = queue.popleft()
            queued.discard(current_url)
            if not unlimited_depth and depth > max_depth:
                _log(f'跳过超出深度限制的 URL: {current_url} (depth={depth})')
                continue
            if current_url in visited:
                continue
            visited.add(current_url)
            future = executor.submit(_fetch_one, (current_url, depth))
            pending[future] = (current_url, depth)
            #_log(f'提交线程: {current_url}, 待处理: {len(queue)}')
            return True
        return False
  
    def _flush_dirty():
        if dirty_html or dirty_links or dirty_failed:
            _log(f'批量保存到 SQLite: {len(dirty_html)} HTML, {len(dirty_links)} links, {len(dirty_failed)} failed, 待处理: {len(queue)}')
            _flush_html_batch(conn, dirty_html)
            dirty_html.clear()
            _flush_links_batch(conn, dirty_links)
            dirty_links.clear()
            _flush_failed_pages_batch(conn, dirty_failed)
            dirty_failed.clear()

    executor = ThreadPoolExecutor(max_workers=max_concurrency)
    try:
        # 初始填满线程池
        while len(pending) < max_concurrency:
            if not _try_submit():
                break

        while pending:
            # 等待至少一个线程完成
            done, _ = wait(pending.keys(), return_when=FIRST_COMPLETED)

            for future in done:
                current_url, depth = pending.pop(future)
                item = future.result()

                if not item:
                    _log(f'未获取到页面: {current_url}')
                    continue

                html = item.get('html', '')
                fetch_error = item.get('error', '')
                content_type = item.get('content_type', '')

                if fetch_error or not content_type:
                    _log(f'抓取页面失败: {current_url}, 错误: {fetch_error}')
                    _append_failed(current_url, fetch_error, html)
                    continue

                if not HTML_CONTENT_TYPE_RE.search(content_type):
                    _log(f'非 HTML 内容类型: {current_url}, content_type={content_type}')
                    _append_failed(current_url, 'not_html_content', html)
                    continue

                if _is_challenge_or_block_page(html):
                    _log(f'挑战或封锁页面: {current_url}')
                    _append_failed(current_url, 'challenge_or_block', html)
                    continue

                if not _is_html_document(html):
                    _log(f'非 HTML 文档: {current_url}')
                    _append_failed(current_url, 'not_html_document', html)
                    continue

                page_index = len(html_cache) + 1
                _log(f"正在保存 HTML文件: {current_url}")
                try:
                    html_path = _save_html_snapshot(
                        current_url,
                        html,
                        outdir,
                        page_index=page_index,
                        timestamp=timestamp,
                    )
                except Exception as e:
                    _log(f'保存 HTML 失败: {current_url}, 错误: {e}')
                    continue

                html_cache.append({'url': current_url, 'html_path': html_path, 'content_type': content_type})
                dirty_html.append({'url': current_url, 'html_path': html_path, 'content_type': content_type})

                links = item.get('links', None)
                if HTML_CONTENT_TYPE_RE.search(content_type) and links is not None:
                    dirty_links[current_url] = links

                if links:
                    for link in links:
                        if link not in visited and link not in failed_urls and link not in queued:
                            cached_path = urlparse(link).path.strip('/')
                            cached_depth = len(cached_path.split('/')) if cached_path else 0
                            if is_file_url(link):
                                _log(f"跳过文件链接: {link}")
                                continue
                            queue.append((link, cached_depth))
                            queued.add(link)

            _flush_dirty()
            # 此线程完成，有空闲槽位，立即提交新任务
            while len(pending) < max_concurrency:
                if not _try_submit():
                    break
    except KeyboardInterrupt:
        _log('抓取被用户中断，正在取消剩余任务...')
        executor.shutdown(wait=False, cancel_futures=True)
    finally:
        executor.shutdown(wait=False)

            

    # 最终刷写
    _flush_html_batch(conn, dirty_html)
    dirty_html.clear()
    _flush_links_batch(conn, dirty_links)
    dirty_links.clear()
    _flush_failed_pages_batch(conn, dirty_failed)
    dirty_failed.clear()
    conn.close()

    # 清理线程池中残留的 Playwright 资源（每个线程独立一份）
    def _cleanup_worker():
        _cleanup_thread_browser()

    cleanup_executor = ThreadPoolExecutor(max_workers=max_concurrency)
    for _ in range(max_concurrency):
        cleanup_executor.submit(_cleanup_worker)
    cleanup_executor.shutdown(wait=True)

    result = {
        'start_url': start_url,
        'saved_count': len(html_cache),
    }
    result['failed_count'] = len(failed_urls)
    return result


def _load_unanalyzed_pages_from_db(start_url: str, outdir: Path) -> list:
    """从 SQLite 加载 video_count = -1 或 video_count > 0 的页面（未分析或已有结果需刷新）。"""
    db_path = _scrape_db_path(start_url, outdir)
    if not db_path.exists():
        return []
    try:
        conn = sqlite3.connect(str(db_path))
        conn.execute("PRAGMA journal_mode=WAL")
        cursor = conn.execute(
            "SELECT url, html_path, content_type FROM pages WHERE video_count = -1 OR video_count > 0"
        )
        pages = []
        for url, html_path, content_type in cursor:
            if html_path:
                p = Path(html_path)
                if not p.is_absolute():
                    p = outdir / p
                html_path = str(p)
            pages.append({'url': url, 'html_path': html_path, 'content_type': content_type})
        conn.close()
        return pages
    except Exception:
        return []


def analyze_saved_html(start_url: str, outdir: Path, progress_callback=None, phase_callback=None, delete_html_no_video=False):
    """读取尚未分析的页面（video_count == -1 && image_count == -1），逐一提取内容并输出 JSON。

    delete_html_no_video: 为 True 时，分析完成后删除不含视频页面的本地 HTML 文件，
    但 SQLite 中的记录保留（video_count 写为 0，不会重复分析）。
    """
    pages = _load_unanalyzed_pages_from_db(start_url, outdir)
    _log(f'Loaded {len(pages)} unanalyzed pages from SQLite.')
    return _analyze_pages_from_cache(
        pages, outdir,
        progress_callback=progress_callback,
        phase_callback=phase_callback,
        start_url=start_url,
        delete_html_no_video=delete_html_no_video,
    )



def _analyze_pages_from_cache(raw_pages, outdir, progress_callback=None, phase_callback=None, start_url=None, delete_html_no_video=False):
    """从页面列表读取已保存 HTML，逐一提取内容并输出 JSON，同时更新 DB 中的 video_count/image_count。
    
    使用有界并发 + 流式处理，避免一次性将所有 HTML 加载到内存中。
    """
    analysis_failed_reasons = {}
    total_videos = 0
    total_image = 0
    total_known_html = len(raw_pages)
    result_pages = []
    deleted_html_count = 0

    if callable(phase_callback):
        phase_callback('analyzing_html')

    # 打开 DB 用于写入统计值
    db_conn = _init_db(_scrape_db_path(start_url, outdir))
    analyze_dir = outdir / 'analyze'
    analyze_dir.mkdir(parents=True, exist_ok=True)
    # 清空 analyze_dir 目录下的所有文件和子目录
    for item in analyze_dir.iterdir():
        if item.is_dir():
            shutil.rmtree(item)
        else:
            item.unlink()

    # ── 多线程提取 content_blocks（流式，不一次性持有所有 future) ──
    def _analyze_one(page):
        """线程内执行：读取 HTML → extract_content_blocks → 计数。
        注意：不返回完整 HTML，只返回计数 + 有视频时的 content_blocks。
        """
        current_url = page['url']
        try:
            content_type = page.get('content_type', '')
            if not HTML_CONTENT_TYPE_RE.search(content_type):
                return {'url': current_url, 'error': 'not_html_content_type', 'video_count': 0, 'image_count': 0}

            if page.get('html_path') is None:
                return {'url': current_url, 'error': 'html_path_is_null', 'video_count': 0, 'image_count': 0}

            src_html_path = Path(page['html_path'])

            html = src_html_path.read_text(encoding='utf-8')
            if _is_challenge_or_block_page(html):
                _log(f'分析时检测到挑战或封锁页面: {current_url}')
                return {'url': current_url, 'error': 'challenge_or_block', 'video_count': 0, 'image_count': 0}
            blocks = extract_content_blocks(html, current_url)
            video_count = sum(1 for b in blocks if isinstance(b, dict) and b.get('type') == 'video')
            image_count = sum(1 for b in blocks if isinstance(b, dict) and b.get('type') == 'image')

            return {
                'url': current_url,
                'content_blocks': blocks,
                'video_count': video_count,
                'image_count': image_count,
                'content_type': content_type,
                'html_path': src_html_path,
                'error': None,
            }

        except Exception as e:
            return {'url': current_url, 'error': str(e), 'video_count': 0, 'image_count': 0}

    max_workers = min(8, len(raw_pages) or 1)
    executor = ThreadPoolExecutor(max_workers=max_workers)
    try:
        # 使用滑动窗口方式提交，只保留有限数量的 future，避免全部 HTML 同时驻留内存
        pending_futures = {}
        page_iter = iter(enumerate(raw_pages, start=1))

        def _submit_next():
            """从迭代器取下一个页面提交，返回是否成功提交。"""
            try:
                idx, page = next(page_iter)
                future = executor.submit(_analyze_one, page)
                pending_futures[future] = (idx, page['url'])
                return True
            except StopIteration:
                return False

        # 初始填满线程池
        for _ in range(max_workers):
            if not _submit_next():
                break

        while pending_futures:
            # 等待任意一个完成
            done, _ = wait(pending_futures.keys(), return_when=FIRST_COMPLETED)

            for future in done:
                idx, current_url = pending_futures.pop(future)
                result = future.result()
                # 立即释放 future 引用（通过 pop 后 future 变量即将被覆盖）
                del future

                if callable(progress_callback):
                    progress_callback(idx, total_known_html, current_url)

                video_count = result.get('video_count', 0)
                image_count = result.get('image_count', 0)

                if result.get('error'):
                    analysis_failed_reasons[current_url] = result['error']

                # 可选：删除不含视频页面的本地 HTML 文件（DB 记录保留）
                if delete_html_no_video and video_count == 0 and not result.get('error'):
                    html_path = result.get('html_path')
                    if html_path:
                        try:
                            hp = Path(html_path)
                            if hp.exists():
                                hp.unlink()
                                deleted_html_count += 1
                                _log(f'删除无视频页面的本地 HTML: {current_url}')
                        except Exception:
                            pass

                # 只有包含视频的页面才保存 HTML + JSON
                if video_count > 0:
                    try:
                        timestamp = result['html_path'].stem.rsplit('_html_', 1)[-1]
                        _save_analyze_output(
                            current_url, result['html_path'], analyze_dir, len(result_pages) + 1, timestamp,
                            content_blocks=result['content_blocks'],
                        )
                    except Exception:
                        analysis_failed_reasons[current_url] = 'save_output_error'
                    else:
                        entry = {
                            'url': current_url,
                            'video_count': video_count,
                            'image_count': image_count,
                        }
                        total_videos += video_count
                        total_image += image_count
                        result_pages.append(entry)

                # 更新 DB 中的统计值
                if db_conn is not None:
                    try:
                        db_conn.execute(
                            "UPDATE pages SET video_count = ?, image_count = ? WHERE url = ?",
                            (video_count, image_count, current_url),
                        )
                        db_conn.commit()
                    except Exception:
                        pass

            # 补充新任务，保持线程池满载
            while len(pending_futures) < max_workers:
                if not _submit_next():
                    break
    except KeyboardInterrupt:
        _log('分析被用户中断，正在取消剩余任务...')
        executor.shutdown(wait=False, cancel_futures=True)
    finally:
        executor.shutdown(wait=False)

    if db_conn is not None:
        db_conn.close()

    summary = {
        'start_url': start_url,
        'page_count': len(result_pages),
        'video_count': total_videos,
        'image_count': total_image,
        'failed_count': len(analysis_failed_reasons),
        'failed_reasons': analysis_failed_reasons,
        'deleted_html_count': deleted_html_count,
    }
    return summary


def scrape_site(
    url: str,
    outdir: Path,
    max_depth: int = 0,
    max_pages: int = 20,
    max_concurrency: int = 1,
    renderer: str = 'auto',
    playwright_headless: bool = True,
    playwright_wait_seconds: float = 5.0,
    playwright_cdp_url: str = '',
    progress_callback=None,
    phase_callback=None,
    delete_html_no_video=False,
):
    save_result = save_site_html(
        url,
        outdir,
        max_depth=max_depth,
        max_pages=max_pages,
        max_concurrency=max_concurrency,
        renderer=renderer,
        playwright_headless=playwright_headless,
        playwright_wait_seconds=playwright_wait_seconds,
        playwright_cdp_url=playwright_cdp_url,
        phase_callback=phase_callback,
    )

    analyze_result = analyze_saved_html(
        url,
        outdir,
        progress_callback=progress_callback,
        phase_callback=phase_callback,
        delete_html_no_video=delete_html_no_video,
    )
    summary = {
        'start_url': url,
        'saved_count': save_result.get('saved_count', 0),
        'failed_count': analyze_result.get('failed_count', 0),
        'page_count': analyze_result.get('page_count', 0),
        'video_count': analyze_result.get('video_count', 0),
        'image_count': analyze_result.get('image_count', 0),
        'failed': list(analyze_result.get('failed_reasons', {}).keys()),
        'failed_reasons': analyze_result.get('failed_reasons', {}),
        'deleted_html_count': analyze_result.get('deleted_html_count', 0),
    }
    return summary
